---
description: "Update a provisioning template (resource: PUT /api/config_templates/:id)"
enabled: true
runner_type: "python-script"
entry_point: 
name: config_templates_update
parameters:
  operation:
    type: string
    default: config_templates.update
    immutable: true
  connection:
    type: string
    description: "Name of <connection> from this pack's configuration that specifies how to connect to a server."
    required: false
  server:
    type: string
    description: "Optional override of the server in <connection> (required if <connection> is not specified)."
    required: false
  username:
    type: string
    description: "Optional override of the username in <connection> (example: username@domain.tld) (required if <connection> is not specified)."
    required: false
  password:
    type: string
    description: "Optional override of the password in <connection>. (required if <connection> is not specified)"
    required: false
    secret: true
  port:
    type: integer
    description: "Optional override of the port in <connection>."
    required: false
  transport:
    type: string
    description: "Optional override of the transport in <connection>."
    required: false
  id:
    type: string
    required: true
  config_template:
    type: object
    required: true
    description: >
       'description: None
        parameters:
            operatingsystem_ids:
              required: false
              type: array
              description: Array of operating system IDs to associate with the template-
            template_combinations_attributes:
              required: false
              type: array
              description: Array of template combinations (hostgroup_id, environment_id)-
            locked:
              required: false
              type: string
              description: Whether or not the template is locked for editing-
            name:
              required: false
              type: string
              description: template name-
            snippet:
              required: false
              type: string
              description:
            template_kind_id:
              required: false
              type: string
              description: not relevant for snippet-
            template:
              required: false
              type: string
              description:
            audit_comment:
              required: false
              type: string
              description:
            location_ids:
              required: false
              type: array
              description: REPLACE locations with given ids-
            organization_ids:
              required: false
              type: array
              description: REPLACE organizations with given ids.-
            '