---
description: "List hosts per environment (resource: GET /api/environments/:environment_id/hosts)"
enabled: true
runner_type: "python-script"
entry_point: lib/action.py
name: environments_hosts_index
parameters:
  operation:
    type: string
    default: environments.hosts_index
    immutable: true
  connection:
    type: string
    description: "Name of <connection> from this pack's configuration that specifies how to connect to a server."
    required: false
  server:
    type: string
    description: "Optional override of the server in <connection> (required if <connection> is not specified)."
    required: false
  username:
    type: string
    description: "Optional override of the username in <connection> (example: username@domain.tld) (required if <connection> is not specified)."
    required: false
  password:
    type: string
    description: "Optional override of the password in <connection>. (required if <connection> is not specified)"
    required: false
    secret: true
  hostgroup_id:
    type: string
    required: false
    description: "ID of host group"
  location_id:
    type: string
    required: false
    description: "ID of location"
  organization_id:
    type: string
    required: false
    description: "ID of organization"
  environment_id:
    type: string
    required: true
    description: "ID of environment"
  search:
    type: string
    required: false
    description: "filter results"
  order:
    type: string
    required: false
    description: "sort results"
  page:
    type: string
    required: false
    description: "paginate results"
  per_page:
    type: string
    required: false
    description: "number of entries per request"